library(turbotracer)

dyntrace_promises({ f<-function() print("Hello")
f()
f<<-function() print("Hello")
f<<-function() print("Hello")
f<<-function() print("Hello")
f<<-function() print("Hello")
f<<-function() print("Hello")
f<<-function() print("Hello")
f<<-function() print("Hello")
f<<-function() print("Hello")
}, "/home/diens/Documents/tools/R_exp/turbotracer/output")
